name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0
