name: tests

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.17
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0
